import Head from 'next/head';
import Image from 'next/image';
import Header from '@/components/header/Header';
import Search from '@/components/Search/Search';
import styles from '@/styles/Home.module.css';

//トップページ（検索画面）
export default function Home() {
  return (
    <>
      <Head>
        <title>GURUMEET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>
        <Image
         src='/KV.jpg' 
         alt="KV"
         fill
         className={styles.kv}
        />
        <Search />
      </main>
    </>
  );
};

